# Generated by Django 5.1.2 on 2024-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('article', 'Article'), ('link', 'Link')], max_length=10)),
                ('content', models.TextField()),
                ('is_shown', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('card_color_light', models.CharField(default='#FFFFFF', max_length=7)),
                ('card_color_dark', models.CharField(default='#000000', max_length=7)),
                ('logo_url', models.CharField(blank=True, max_length=100)),
                ('banner_url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
