# Generated by Django 5.1.2 on 2024-10-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
